Repository tomasnorre/crawler, pull requests merged in 2022-10, with the labels that each got.

#880 [!!!][TASK] Remove icon registration via ext_localconf.php
  Classes/Utility/BackendUtility.php
  ext_localconf.php
Labels: hacktoberfest-accepted, breaking

#950 [CI] Add PHP7.4 for scrutinizer coverage upload
  .github/workflows/Tests.yml
Labels: hacktoberfest-accepted

#954 [CI] Switch to php-coveralls/php-coveralls for PHP 8 support
  .github/workflows/Coveralls.yml
Labels: hacktoberfest-accepted

#956 [CI] Update Scrutinizer to PHP 8.0
  .scrutinizer.yml
Labels: hacktoberfest-accepted

#961 [BUGFIX] If indexed_search is installed activate procInstructions for indexed_search
  CHANGELOG.md
  ext_localconf.php
Labels: v11.x, backport
